#pragma once

// generated by .\ddl2cpp .\a.sql dbschema polih

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace polih
{
  namespace Data_
  {
    struct EntryId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "entry_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T entryId;
            T& operator()() { return entryId; }
            const T& operator()() const { return entryId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct DeviceId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "device_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T deviceId;
            T& operator()() { return deviceId; }
            const T& operator()() const { return deviceId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Ph
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ph";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ph;
            T& operator()() { return ph; }
            const T& operator()() const { return ph; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace Data_

  struct Data: sqlpp::table_t<Data,
               Data_::EntryId,
               Data_::DeviceId,
               Data_::Ph>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "data";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T data;
        T& operator()() { return data; }
        const T& operator()() const { return data; }
      };
    };
  };
  namespace Devices_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct Password
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "password";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T password;
            T& operator()() { return password; }
            const T& operator()() const { return password; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text>;
    };
    struct DeviceName
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "device_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T deviceName;
            T& operator()() { return deviceName; }
            const T& operator()() const { return deviceName; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace Devices_

  struct Devices: sqlpp::table_t<Devices,
               Devices_::Id,
               Devices_::Password,
               Devices_::DeviceName>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "devices";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T devices;
        T& operator()() { return devices; }
        const T& operator()() const { return devices; }
      };
    };
  };
} // namespace polih
